### ISSUE TITLE
mssql error

### ISSUE THREAD

**Issue by digitalsadhu** [slively/loopback-db-migrate#3]
Currently its not possible to use looback-db-migrate with the mssql connector. 

This seems to be because a 'uniqueidentifier' column is created as a pk and that will not accept a string of characters. 

`RequestError: Conversion failed when converting from a character string to uniqueidentifier.`

I believe you need to create your Migration model with a mapping for mssql where the name column is explicitly set to be something like an nvarchar.

**Comment by digitalsadhu** [comment]
I found the only way I could get mssql to stop creating the `name` column as data type `uniqueidentifier` was to remove `"id": true,` from the Migration model definition. After I did this, things began working correctly

**Comment by trosen333** [comment]
we have noticed that this error occurs also when using mongoDB. removing the  "id": true, from the Migration model definition also worked for us.
