### ISSUE TITLE
Incompatible with mongodb

### ISSUE THREAD

**Issue by cookejames** [slively/loopback-db-migrate#8]
The definition of name in the model causes unexpected behaviour when using mongodb:
    "name": {
        "id": true,
        "type": "String",
        "required": true,
        "length": 100,
        "index": {
            "unique": true
        }
    },
Strictly this is a bug in the mongodb connector but the id, name, is transformed to the key _id however the index for name isn't. The first database insert works fine but the second insert of migration data doesn't as it complains the values for name are not unique (in mongo if a field has a unique insert but isn't present in the document it is given a null value).

My workaround is to remove the unique index as id is already indexed.

**Comment by doublemarked** [comment]
I've had a pull request solving this exact issue sitting there for about a month....

https://github.com/slively/loopback-db-migrate/pull/6

**Comment by cookejames** [comment]
Ha, just saw that. On mongodb unique isn't required for an index. I would expect that for mysql using index: true would set the field as the primary key so unique isn't required but I've never used stringloop with that.

**Comment by doublemarked** [comment]
Yes, that's my feeling also.
